name: Trigger Target Repo
on:
  push:
    branches: [main]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository_owner }}/compiledUserscripts/dispatches \
            -d '{
              "event_type": "source_push",
              "client_payload": {
                "repository": "${{ github.repository }}",
                "sha": "${{ github.sha }}"
              }
            }'
